# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4863fd91741811c32c6742a9494c5a38b8fcedcdd982894a15d675838b743d9dc72c360bfaec8e7a56645bb6a92611c7f87b60a1670568325aa2ceb8a467d54

test:
  secret_key_base: 7a0df60c7e73c75cbaca3ab03bbff8752eb9520bbc5edf24c91953e458839cc0fa38f5be2faeed752b5f6b50c9f9360cd3fdda674fb09cf407672bda87ae98bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
